<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_platform</name>
   <tag></tag>
   <elementGuidId>e1b1af2d-68f7-4101-ae5e-87349f060fa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dashboard.vh-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5efebb97-fde4-4420-9e39-92a83434d0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dashboard vh-100</value>
      <webElementGuid>f2cd88f4-2b85-4a6c-8854-8c8d3b97e712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>platform</value>
      <webElementGuid>455686c6-5053-4096-b37e-3a34bc8392c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;dashboard vh-100&quot;]</value>
      <webElementGuid>ff305287-97d3-43ee-911f-674b85938251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
      <webElementGuid>12fab621-745b-4ee5-be68-7569dc4f9735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'root', '&quot;', ')/div[@class=', '&quot;', 'dashboard vh-100', '&quot;', ']')])[1]/preceding::div[4]</value>
      <webElementGuid>be62b56c-a02d-44fe-b949-0f6e29c71fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>33089538-7a82-4c03-8b97-095e32e26dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'platform' or . = 'platform')]</value>
      <webElementGuid>ff5831d5-6d3e-489d-87ff-c5f27872aed7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
